# Generated by Django 4.2.25 on 2025-10-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('artist', models.CharField(default='АСИЯ', max_length=150, verbose_name='Исполнитель')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('audio', models.FileField(upload_to='tracks/', verbose_name='Аудио')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='tracks/', verbose_name='Обложка')),
                ('lyrics', models.TextField(blank=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['order', 'id'],
            },
        ),
    ]
