# Generated by Django 4.2.26 on 2025-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата концерта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('venue', models.CharField(max_length=200, verbose_name='Место проведения')),
                ('ticket_url', models.URLField(verbose_name='Ссылка на билеты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Концерт',
                'verbose_name_plural': 'Концерты',
                'ordering': ['date'],
            },
        ),
    ]
